# Use the official Node.js image as the base image
FROM node:14

# Set the working directory
WORKDIR /client

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3000

# Start the app in development mode
CMD ["npm", "run", "dev"]