version: '3'
services:
  frontend:
    container_name: problem-hub-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
      - /client/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    container_name: problem-hub-backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    environment:
      - DEBUG=True
