version: '3'
services:
  frontend:
    container_name: problem-hub-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # File syncing
      - ./client:/client
      - /client/node_modules
      - /client/.next
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    restart: unless-stopped
    container_name: problem-hub-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    environment:
      - DEBUG=True
