version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - DEBUG=True

  migrations:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: python manage.py migrate
    depends_on:
      - backend
    restart: "no"

  cmd:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: /bin/bash
    stdin_open: true
    tty: true