# Use the official Python image as the base image
FROM python:3.9

# Set the working directory
WORKDIR /server

# Copy requirements.txt
COPY requirements.txt .

# add missing
COPY ./ ./

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port the app runs on (default is 8000)
EXPOSE 8000

# Define a command to run the app using Django's development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]