# Generated by Django 4.2.4 on 2023-10-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_alter_problem_user_alter_uploadedfile_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="path_to_file",
        ),
        migrations.AddField(
            model_name="problem",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problems",
                to="server.uploadedfile",
            ),
        ),
    ]
