# Generated by Django 4.2.4 on 2023-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_remove_problem_path_to_file_problem_uploaded_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="uploaded_file",
        ),
        migrations.AddField(
            model_name="problem",
            name="file",
            field=models.FileField(default=1, upload_to="."),
            preserve_default=False,
        ),
    ]
